### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by katjamarina** [katjamarina/APPR-2017-18#1]
Pozdravljeni, 
zanima me, če sem vse tabele pravilno uredila, ali so potrebne še kakšne spremembe?
Hvala

**Comment by jaanos** [comment]
Uvožene tabele izgledajo v redu. Sedaj lahko urediš še poročilo ter vanj na podlagi uvoženih podatkov izrišeš nekaj grafov in zemljevidov, da boš pripravljena na predstavitev naslednji teden.
