### ISSUE TITLE
Napredna analiza

### ISSUE THREAD

**Issue by katjamarina** [katjamarina/APPR-2017-18#5]
Pozdravljeni, 
v projekt bi dodala še napredno analizo, in sicer bi rada vključila grupiranje s parametroma zaposljivost in delež, tako da bi imela npr. 4 skupine, ena skupina bi vsebovala države, ki več vlagajo v visokošolstvo in imajo visoko zaposljivost, druga manj v visokošolstvo in vseeno visoko zaposljivost, tretja nizka zap. in več vlagajo, četrta nizka zap. in manj vlagajo. 
Poskušala sem s clusteringom, a ne vem točno, kako deluje to grupiranje.

Lep pozdrav, Katja

**Comment by jaanos** [comment]
Clustering deluje nekako tako: tvoje podatke si predstavljaš kot točke v prostoru ustrezne dimenzije (v tvojem primeru sta podatka dva, tako da imaš točke v ravnini) - skupine potem sestavljajo točke, ki so bližje skupaj (ne nujno tako, kot si si zamislila). Za občutek si lahko izrišeš graf, kjer je lepo vidno, kakšna je razdelitev v skupine:
```R
ggplot(inner_join(skupine1, grupe), aes(x = delez.x, y = delez.y, color = skupina)) + geom_point()
```

Mimogrede: pri izrisovanju zemljevida obrni vrstni red združevanja (ali pa uporabi `right_join`), da se ti izrišejo tudi države, za katere nimaš podatkov. Da ti zaradi ruskih ozemelj vzhodno od 180. poldnevnika čez zemljevid ne bo izrisovalo vodoravnih črt, lahko ustrezno filtriraš točke, npr.
```R
grupe_zemljevid <- ggplot() + geom_polygon(data = zemljevid %>% filter(long > -30) %>%
                                             left_join(skupine1, by = c("NAME_LONG" = "drzava")),
                        aes(x = long, y = lat, group = group, 
                            fill = skupina)) +
  coord_map(xlim = c(-25, 40), ylim = c(32, 72))
```
Opažam še, da se v poročilu in programu sklicuješ na razpredelnico `bdp.slo`, ki pa ni nikjer definirana. Verjetno si hotela uporabiti `uvozi_bdp.slo`?

**Comment by katjamarina** [comment]
Ali lahko vprašam, na kakšen način pa bi lahko potem združila, kakor sem si prej zamislila?

**Comment by jaanos** [comment]
Lahko bi si sama določila meje in na podlagi tega države razdelila v kategorije. Sicer pa na ta način ne dobiš nujno nekih "naravnih" skupin, saj se ti lahko zgodi, da meje niso najbolje nastavljene in so potem lahko npr. pojavljajo večje razlike znotraj ene skupine kot pa med skupinami.

S clusteringom dosežeš ravno to, da minimiziraš razlike znotraj skupin. Potem lahko na podlagi dobljene razvrstitve ugotavljaš, kakšne so karakteristike skupine. Zato svetujem, da za vsako državo vključiš še več podatkov (kot vidim, imaš za vsako državo še podatka o deležu zaposlenih za dve trajanji iskanja zaposlitve), potem pa narediš clustering in analiziraš, kaj se dogaja v vsaki skupini (seveda lahko poskusiš tudi z različnimi števili skupin).

**Comment by katjamarina** [comment]
Imam še eno vprašanje, v zemljevidu pri napredni analizi mi v legendi označi tudi NA, kako se tega znebim?
Hvala

**Comment by jaanos** [comment]
Katere vrednosti se prikažejo v legendi, lahko nastaviš s `scale_fill_discrete` (oziroma ustrezno funkcijo glede na tip legende), npr.
```R
grupe.zemljevid + scale_fill_discrete(breaks = sort(skupine1$skupina))
```
