### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by katjamarina** [katjamarina/APPR-2017-18#6]
Pozdravljeni!

S facet_grid sem hotela združiti zemljevida za podatke moških/žensk, a mi izriše še tretji zemljevid z vrednostmi NA, čeprav v tabeli nimam nobenih manjkajočih vrednosti. Kako bi lahko rešila težavo?
![1af54cb1-b0ab-47a2-9169-052e3ba03603](https://user-images.githubusercontent.com/28740027/40534033-f4849660-6004-11e8-9847-9f44a55d61a5.jpeg)

Katja

**Comment by jaanos** [comment]
Sklepam, da podatke pridružuješ k zemljevidu z `left_join` ali `right_join`. Kar se zgodi je to, da se za države, za katere nimaš podatkov, za spol (in ostale vrednosti) pojavi `NA` in se zato ta vrednost pojavi posebej.

Ena možnost bo torej, da namesto katere od zgornjih funkcij uporabiš `inner_join`, a se zaradi tega države brez podatkov ne bodo izrisale. Druga možnost bi bila, da z `inner_join` zemljevidu pridružiš stolpec s spolom (tako bo vsaka točka podvojena), potem pa še pridružiš svoje podatke:
```R
ggplot() + geom_polygon(data = zemljevid %>% inner_join(data.frame(LEVEL = 2, spol = c("M", "Z"))) %>%
                          left_join(procenti, by = c("NAME_LONG" = "drzava", "spol" = "spol")),
                        aes(x = long, y = lat, group = group, fill = delez)) + facet_grid(~ spol) +
  coord_cartesian(xlim = c(-22, 40), ylim = c(30, 70)) + ggtitle("Delež zaposlenih po spolu")
```
Tukaj je uporabljena spremenljivka `LEVEL` zgolj zato, da ima `inner_join` po čem združevati - izbran je bil taka stolpec iz zemljevida, ki ima samo eno vrednost (tako se nič ne izgubi).
